apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: beepsort-cert
  namespace: beepsort
spec:
  secretName: beepsort-cert
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "beepsort.polsevev.dev"

